# Site settings
name: Wenheng Gao
title: Wenheng "Sylvia" Gao | UI/UX Designer
description: A human-centered designer aiming at making magnificent UI/UX.
url: https://sylgaw.github.io/
baseurl: ''
email: sylvia619@berkeley.edu
cover: https://sylgaw.github.io/img/og.png
logo: https://sylgaw.github.io/img/emojis/technologist.png
resume: https://sylgaw.github.io/resume.pdf
social:
  - title: email
    url: mailto:sylvia619@berkeley.edu
  - title: twitter
    url: https://twitter.com/
  - title: instagram
    url: https://instagram.com/sylviaww_gao
  - title: codepen
    url: http://codepen.io/
  - title: github
    url: https://github.com/SylGaw
  - title: linkedin
    url: https://www.linkedin.com/in/wenheng-gao-9443ab1ba

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
